;;; desktop+-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from desktop+.el

(autoload 'desktop+-create "desktop+" "\
Create a new session, identified by a name.
The session is created in a subdirectory of `desktop+-base-dir'.
It can afterwards be reloaded using `desktop+-load'.

As a special case, if NAME is left blank, the session is
automatically named after the current working directory.

(fn NAME)" t)
(autoload 'desktop+-create-auto "desktop+" "\
Create a new session, identified by the current working directory.
The session is created in a subdirectory of `desktop+-base-dir'.
It can afterwards be reloaded using `desktop+-load'." t)
(autoload 'desktop+-load "desktop+" "\
Load a session previously created using `desktop+-create'.
NAME is the name which was given at session creation.  When
called interactively, it is asked in the minibuffer with
auto-completion.

As a special case, if NAME is left blank, the session is
automatically named after the current working directory.

(fn NAME)" t)
(autoload 'desktop+-load-auto "desktop+" "\
Load a session previously created using `desktop+-create-auto'.
The session is identified by the current working directory." t)
(autoload 'desktop+--advice--desktop-save "desktop+" "\
Also save special buffers.

(fn &rest ARGS)")
(advice-add 'desktop-save :before #'desktop+--advice--desktop-save)
(autoload 'desktop+--advice--desktop-restore-frameset "desktop+" "\
Restore special buffers.

(fn &rest ARGS)")
(advice-add 'desktop-restore-frameset :before #'desktop+--advice--desktop-restore-frameset)
(register-definition-prefixes "desktop+" '("desktop+-"))

;;; End of scraped data

(provide 'desktop+-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; desktop+-autoloads.el ends here
